// <auto-generated />
namespace ResourceBox.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EntradaEResponsavelModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntradaEResponsavelModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201709192052248_EntradaEResponsavelModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
